### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by naveen521kk** [naveen521kk/chocolatey-texlive#2]
I did a commit https://github.com/naveen521kk/chocolatey-texlive/commit/f938ef200952ceeb078c4e95944d88bd5f05bc33
and the CI is failing with an error
```sh
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Undefined subroutine &TeXLive::TLWinGoo::is_vista called at C:/tools/tlpkg/TeXLive/TLWinGoo.pm line 1340, <PROFILE> line 3.
```
removing the PowerShell reference, I think it should be a problem with the installer
```sh
Undefined subroutine &TeXLive::TLWinGoo::is_vista called at C:/tools/tlpkg/TeXLive/TLWinGoo.pm line 1340, <PROFILE> line 3.
```
@norbusan do you know what happened?

**Comment by norbusan** [comment]
Should be fixed by now in the repo

**Comment by naveen521kk** [comment]
Thanks :+1:
