### ISSUE TITLE
Error: Can't install or Update TexLive

### ISSUE THREAD

**Issue by BradKML** [naveen521kk/chocolatey-texlive#3]
C:\WINDOWS\system32>choco install texlive --yes
Chocolatey v0.10.15
Installing the following packages:
texlive
By installing you accept licenses for the packages.
Progress: Downloading texlive 2021.20210402... 100%

texlive v2021.20210402 [Approved]
texlive package files install completed. Performing other installation steps.
Writing Profile
Writing Profile using Passed Parameters.
TeX Live Profile will be written to C:\tools\texlive.profile
Extracting C:\ProgramData\chocolatey\lib\texlive\tools\install-tl.zip to C:\tools...
C:\tools
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot create a file when that file already exists.

The install of texlive was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\texlive\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - texlive (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\texlive\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by naveen521kk** [comment]
@BrandonKMLee can you send `C:\ProgramData\chocolatey\logs\chocolatey.log`? It should have some debug info.

I think the install should have failed over at https://github.com/naveen521kk/chocolatey-texlive/blob/master/texlive/tools/chocolateyinstall.ps1#L52, which makes me think, did you try installing this package previously?

**Comment by BradKML** [comment]
@naveen521kk removed, then reinstalled.
[log.log](https://github.com/naveen521kk/chocolatey-texlive/files/6372398/log.log)

**Comment by naveen521kk** [comment]
I found what is happening, will push a fix soon.

**Comment by naveen521kk** [comment]
For now, you can remove `C:\tools\install-tl` directory and then proceed to install normally.

**Comment by naveen521kk** [comment]
In https://community.chocolatey.org/packages/texlive/2021.20210425 this should be fixed.
