### ISSUE TITLE
About the `install-tl` parameters.

### ISSUE THREAD

**Issue by looong-cat** [naveen521kk/chocolatey-texlive#7]
Hi, thanks for your contribution!
I noticed that when using choco for installation, it seems that only `Package Specific Parameters` can be used?
I understand that it is writing the parameters into `texlive.profile`.

I observed that choco is performing the installation with the command
`perl "C:\tools\install-tl-30052216\install-tl" -no-gui -profile C:/tools/texlive.profile`

However, if I want to use more of install-tl's original parameters e.g.
`install-tl --location -repository`
Is it possible to achieve this through choco specific command format?

**Comment by naveen521kk** [comment]
I don't think you can pass additional parameters to the installer. Briefly looking at https://www.tug.org/texlive/doc/install-tl.html I could see only `-repository` is useful and others are something, people, won't use much and could abort the installation. Do you want to specify the exact parameters through choco or just a parameter for supporting `repository`?

**Comment by norbusan** [comment]
@foxh1s I am the author of install-tl (and the rest of TL infra) - what would you want to change?

I am currently testing changes to the installer to make `TEXDIR`, `TEXMFHOME`, `TEXMFLOCAL`, `TEXMFVAR`, `TEXMFCONFIG` settings configurable via command line parameters, but this is not released by now.

**Comment by naveen521kk** [comment]
If I understand correctly, they want to pass extra command-line arguments to `install-tl` like `-repository` which they can't do when using installing using chocolatey at the moment.

> I am currently testing changes to the installer to make TEXDIR, TEXMFHOME, TEXMFLOCAL, TEXMFVAR, TEXMFCONFIG settings configurable via command line parameters, but this is not released by now.

In which case, I guess, allowing the user to pass arbitrary command-line parameters to the installer should be implemented. I'll implement it when I get time this week.

**Comment by looong-cat** [comment]
> @foxh1s I am the author of install-tl (and the rest of TL infra) - what would you want to change?
> 
> I am currently testing changes to the installer to make `TEXDIR`, `TEXMFHOME`, `TEXMFLOCAL`, `TEXMFVAR`, `TEXMFCONFIG` settings configurable via command line parameters, but this is not released by now.

@norbusan 
Great Job!
I don't want to add more functions for `install-tl`. 
Instead, I hope when using `choco` to install `texlive`, the parameters owned by `install-tl` could be delivered to `chocolatey`. 
@naveen521kk 
https://github.com/naveen521kk/chocolatey-texlive/issues/7#issuecomment-1141224766

Due to our network issue, we are creating a CTAN mirror on the intranet, which could be available for our colleagues. 

I have read the manual of texlive, and learned that `--location`[①](https://tug.org/texlive/quickinstall.html) and `-repository`[②](https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-26025r8) could use the specified mirror.
Though I am not sure the difference between `--location` parameters and `-repository` parameters, I used them both and they seem to work fine now... 
I guess `--location` is used during network installation, while `-repository` is the mirror of `tlmgr`?

chocolatey is very fantastic, and many complex things can be solved with just one line of command. 
Besides, I don't want to create many huge copies of `texlive.iso`, that's not cool…

**Comment by norbusan** [comment]
Ok, this is then up to @naveen521kk to fix, nothing I can do. More than happy about that ;-)

Concerning `--location` versus `--repository`, they are both the same (as well as `--repo` and `--repos`), just here for backward compatibility due to naming in very early versions.

**Comment by looong-cat** [comment]
> Ok, this is then up to @naveen521kk to fix, nothing I can do. More than happy about that ;-)
> 
> Concerning `--location` versus `--repository`, they are both the same (as well as `--repo` and `--repos`), just here for backward compatibility due to naming in very early versions.

I get it, thank you!

**Comment by naveen521kk** [comment]
For starters, atleast till I implement this feature, I think the repository can be changed by setting an environment variable. Is that correct @norbusan?

**Comment by norbusan** [comment]
Sorry no, that is not possible ATM. Only the installation destination can be changed via env vars.

**Comment by naveen521kk** [comment]
> Sorry no, that is not possible ATM. Only the installation destination can be changed via env vars.

Ah, okay. I though there exists environment variables to change that...

**Comment by naveen521kk** [comment]
I've pushed `2022.20220601` which should support the parameter `InstallerParameters` where you can pass the extra parameter you want to pass to the installer.
For example, for setting the repository to https://mirrors.mit.edu/CTAN/systems/texlive/tlnet/, you can run `choco install texlive --params="'/InstallerParameters:--repository="https://mirrors.mit.edu/CTAN/systems/texlive/tlnet/"'"`. You should wait for the version to be approved first which would be automatically done in a few hours.

**Comment by looong-cat** [comment]
> I've pushed `2022.20220601` which should support the parameter `InstallerParameters` where you can pass the extra parameter you want to pass to the installer. For example, for setting the repository to https://mirrors.mit.edu/CTAN/systems/texlive/tlnet/, you can run `choco install texlive --params="'/InstallerParameters:--repository="https://mirrors.mit.edu/CTAN/systems/texlive/tlnet/"'"`. You should wait for the version to be approved first which would be automatically done in a few hours.

Great. Thanks!
After the new version is updated in chocolatey's repository, I will test it and let you know my results.

**Comment by looong-cat** [comment]
> I've pushed `2022.20220601` which should support the parameter `InstallerParameters` where you can pass the extra parameter you want to pass to the installer. For example, for setting the repository to https://mirrors.mit.edu/CTAN/systems/texlive/tlnet/, you can run `choco install texlive --params="'/InstallerParameters:--repository="https://mirrors.mit.edu/CTAN/systems/texlive/tlnet/"'"`. You should wait for the version to be approved first which would be automatically done in a few hours.

Version `2022.20220601` in the chocolatey repository, I have tested the `-repository` parameter and it works fine (I have not tested more parameters).
